apiVersion: apps.innoq.com/v1
kind: MyApp
metadata:
  name: myapp
spec:
  image: app
  commandArgs: ["$(MY_SERVICE_NAME)"]
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
  - port: 8080
    targetPort: 8080
